version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 

  gateway:
    build:
      context: ./backend/gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - user-service
      - post-service
      - comment-service

  user-service:
    build:
      context: ./backend/services/userService
      dockerfile: Dockerfile
    container_name: blog-user
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq

  post-service:
    build:
      context: ./backend/services/postService
      dockerfile: Dockerfile
    container_name: blog-post
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq

  comment-service:
    build:
      context: ./backend/services/commentService
      dockerfile: Dockerfile
    container_name: blog-comment
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
